<?php
/** @var \Techyouknow\SocialLogin\Block\SocialBlock $block */
?>

<?php if ($block->isSocialLoginActive() && count($block->getEnabledSocialNetworks()) > 0): ?>
<div class="block block-social-login">
    <div class="social-login-container">
        <div class="seperator">
            <strong><?= $block->escapeHtml(__('or')) ?></strong>
        </div>
        <div class="block-content" aria-labelledby="block-customer-login-heading">
            <ul>
                <?php foreach ($block->getEnabledSocialNetworks() as $key => $socialNetwork): ?>
                <li>
                    <a class="<?= $block->escapeHtmlAttr($key) ?>"
                       href="<?= $block->escapeUrl($block->getUrl('customer/social/login', ['provider' => $key])) ?>">
                        <span><?= $block->escapeHtml(__('Sign in with %1', $socialNetwork)) ?></span>
                    </a>
                </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
</div>
<?php endif; ?>
